apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-v2-pvc
spec:
  storageClassName: longhorn-v2-data-engine
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
