apiVersion: v1
kind: Pod
metadata:
  name: fio
spec:
  containers:
    - name: fio
      image: nixery.dev/shell/fio
      args:
        - sleep
        - infinity
      volumeMounts:
        - mountPath: /cephfs-volume
          name: cephfs-volume
  volumes:
    - name: cephfs-volume
      persistentVolumeClaim:
        claimName: cephfs-pvc
