apiVersion: v1
kind: Pod
metadata:
  name: fio
spec:
  containers:
    - name: fio
      image: nixery.dev/shell/fio
      args:
        - sleep
        - infinity
      volumeMounts:
        - name: cephfs-vol
          mountPath: /cephfs-volume
        - name: ceph-rbd-vol
          mountPath: /ceph-rbd-volume
  volumes:
    - name: cephfs-vol
      persistentVolumeClaim:
        claimName: cephfs-pvc
    - name: ceph-rbd-vol
      persistentVolumeClaim:
        claimName: ceph-rbd-pvc
