apiVersion: v1
kind: Pod
metadata:
  name: fio
spec:
  containers:
    - name: fio
      image: nixery.dev/shell/fio
      command:
        - sleep
        - infinity
      volumeMounts:
        - name: openebs-mayastor-vol
          mountPath: /openebs-mayastor-volume
  volumes:
    - name: openebs-mayastor-vol
      persistentVolumeClaim:
        claimName: openebs-mayastor-pvc
